CREATE TABLE IF NOT EXISTS MEMBER
(
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(50),
    CREATION_DATE TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DEALERSHIP (
    ID VARCHAR(36) PRIMARY KEY,
    TRADE_NAME VARCHAR(255),
    CNPJ VARCHAR(14),
    CREATION_DATE TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DEALERSHIP_MEMBER (
    DEALERSHIP_ID VARCHAR(36),
    MEMBER_ID VARCHAR(36),
    PRIMARY KEY (DEALERSHIP_ID, MEMBER_ID),
    FOREIGN KEY (DEALERSHIP_ID) REFERENCES DEALERSHIP(ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID)
);

CREATE TABLE IF NOT EXISTS VEHICLE (
    ID VARCHAR(36) PRIMARY KEY,
    DEALERSHIP_ID VARCHAR(36),
    LICENSE_PLATE VARCHAR(10),
    BRAND_TYPE VARCHAR(255),
    MODEL VARCHAR(255),
    MANUFACTURING_YEAR VARCHAR(4),
    MODEL_YEAR VARCHAR(4),
    VERSION VARCHAR(255),
    TRANSMISSION_TYPE VARCHAR(50),
    FUEL_TYPE VARCHAR(50),
    DOORS INT,
    COLOR VARCHAR(50),
    CREATION_DATE TIMESTAMP,
    FOREIGN KEY (DEALERSHIP_ID) REFERENCES DEALERSHIP(ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(20),
    CREATION_DATE TIMESTAMP
);

CREATE TABLE IF NOT EXISTS OPPORTUNITY (
    ID VARCHAR(36) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(36),
    DEALERSHIP_ID VARCHAR(36),
    MEMBER_ID VARCHAR(36),
    STATUS VARCHAR(50),
    REASON VARCHAR(255),
    VEHICLE_ID VARCHAR(36),
    CREATION_DATE TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    FOREIGN KEY (DEALERSHIP_ID) REFERENCES DEALERSHIP(ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(ID)
);


